version: "3"
services:
  seata-server:
    image: seataio/seata-server:1.6.1
    hostname: seata-server
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      # 可不用, 会从配置中心读取, 加上这个万一配置中心配置有问题加载不到配置时会报错可提前发现问题
      - STORE_MODE=db
      # 以SEATA_IP作为host注册到注册中心，使用宿主机ip
      - SEATA_IP=192.168.50.15
      - SEATA_PORT=8091
      #- SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - ./resources:/seata-server/resources