server:
  port: 80

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blankhang.account.entity,com.blankhang.account.object
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.15:3306/seata_business?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    tomcat:
      initial-size: 5
      max-active: 100
      min-idle: 5
      # 获取连接时要不要对该连接进行有效性校验
      test-on-borrow: false
      # 归还连接时要不要对该连接进行有效性校验
      test-on-return: false
      # 是否需要检查空闲的连接有效性
      test-while-idle: true
      # 用来检测连接是否有效的sql
      validation-query: select 1
      # 配置间隔多久才进行一次检测, 检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 3000
      # 一个连接在池中最小生存的时间, 单位是毫秒
      min-evictable-idle-time-millis: 600000

  application:
    name: business
  cloud:
    nacos:
      discovery:
        server-addr: ${meta.seata.nacos.server-addr}
        username: ${meta.seata.nacos.username}
        password: ${meta.seata.nacos.password}
        namespace: ${meta.seata.nacos.namespace}
        group: ${meta.seata.nacos.group}

logging:
  level:
    com.blankhang.account: debug


# seata服务注册信息, 用于下面引用, 避免重复粘贴
meta:
  seata:
    nacos:
      server-addr: 192.168.50.15:8848
      namespace: 82eca4a8-ef2f-488e-9ebd-cb70bb2f060a
      group: SEATA_GROUP
      username: nacos
      password: nacos

seata:
  enabled: true
  application-id: business
  # 事务分组, 后面细讲
  tx-service-group: default_tx_group
  registry:
    type: nacos
    nacos:
      # 应与seata-server实际注册的服务名一致
      application: seata-server
      server-addr: ${meta.seata.nacos.server-addr}
      namespace: ${meta.seata.nacos.namespace}
      group: ${meta.seata.nacos.group}
      username: ${meta.seata.nacos.username}
      password: ${meta.seata.nacos.password}

  config:
    type: nacos
    nacos:
      server-addr: ${meta.seata.nacos.server-addr}
      namespace: ${meta.seata.nacos.namespace}
      group: ${meta.seata.nacos.group}
      username: ${meta.seata.nacos.username}
      password: ${meta.seata.nacos.password}
